name: Docker Image CI

on:
  pull_request:
    branches: [master]

jobs:
  pytorch-notebook-cpu:
    runs-on: [self-hosted, pytorch-notebook]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create shot SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ./Dockerfile
          tags: ghcr.io/kbc8894/pytorch-notebook:cpu-${{ steps.short-sha.outputs.sha }}
          no-cache: true
