name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  pytorch-notebook-cpu:
    runs-on: [self-hosted, pytorch-notebook]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push pytorch-notebook:cpu
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/kbc8894/pytorch-notebook:latest
            ghcr.io/kbc8894/pytorch-notebook:cpu
            ghcr.io/kbc8894/pytorch-notebook:cpu-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Build and push pytorch-notebook:cpu-kubeflow
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile.kubeflow
          tags: |
            ghcr.io/kbc8894/pytorch-notebook:kubeflow
            ghcr.io/kbc8894/pytorch-notebook:kubeflow-latest
            ghcr.io/kbc8894/pytorch-notebook:cpu-kubeflow
            ghcr.io/kbc8894/pytorch-notebook:cpu-kubeflow-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_CONTAINER=ghcr.io/kbc8894/pytorch-notebook:cpu-latest

  pytorch-notebook-gpu:
    runs-on: [self-hosted, pytorch-notebook]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push base-notebook:gpu
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./docker-stacks/base-notebook
          file: ./docker-stacks/base-notebook/Dockerfile
          tags: ghcr.io/kbc8894/base-notebook:gpu-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            ROOT_CONTAINER=nvidia/cuda:11.1-cudnn8-runtime-ubuntu18.04
      - name: Build and push minimal-notebook:gpu
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./docker-stacks/minimal-notebook
          file: ./docker-stacks/minimal-notebook/Dockerfile
          tags: ghcr.io/kbc8894/minimal-notebook:gpu-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_CONTAINER=ghcr.io/kbc8894/base-notebook:gpu-latest
      - name: Build and push scipy-notebook:gpu
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./docker-stacks/scipy-notebook
          file: ./docker-stacks/scipy-notebook/Dockerfile
          tags: ghcr.io/kbc8894/scipy-notebook:gpu-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_CONTAINER=ghcr.io/kbc8894/minimal-notebook:gpu-latest
      - name: Build and push pytorch-notebook:gpu
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile.gpu
          tags: |
            ghcr.io/kbc8894/pytorch-notebook:gpu
            ghcr.io/kbc8894/pytorch-notebook:gpu-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_CONTAINER=ghcr.io/kbc8894/scipy-notebook:gpu-latest
      - name: Build and push pytorch-notebook:gpu-kubeflow
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile.kubeflow
          tags: |
            ghcr.io/kbc8894/pytorch-notebook:gpu-kubeflow
            ghcr.io/kbc8894/pytorch-notebook:gpu-kubeflow-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_CONTAINER=ghcr.io/kbc8894/pytorch-notebook:gpu-latest
